export function WeischerLogo({ className }: { className?: string }) {
  return (
    <svg
      className={className}
      viewBox="0 0 40 40"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden="true"
    >
      <title>Weischer Logo</title>
      <rect
        x="4"
        y="8"
        width="32"
        height="20"
        rx="2"
        fill="#8b1a3f"
        opacity="0.9"
      />
      <rect x="6" y="10" width="28" height="16" rx="1" fill="#0c0a0b" />
      <rect
        x="8"
        y="5"
        width="3"
        height="3"
        rx="0.5"
        fill="#8b1a3f"
        opacity="0.4"
      />
      <rect
        x="14"
        y="5"
        width="3"
        height="3"
        rx="0.5"
        fill="#8b1a3f"
        opacity="0.4"
      />
      <rect
        x="20"
        y="5"
        width="3"
        height="3"
        rx="0.5"
        fill="#8b1a3f"
        opacity="0.4"
      />
      <rect
        x="26"
        y="5"
        width="3"
        height="3"
        rx="0.5"
        fill="#8b1a3f"
        opacity="0.4"
      />
      <rect
        x="8"
        y="31"
        width="3"
        height="3"
        rx="0.5"
        fill="#8b1a3f"
        opacity="0.4"
      />
      <rect
        x="14"
        y="31"
        width="3"
        height="3"
        rx="0.5"
        fill="#8b1a3f"
        opacity="0.4"
      />
      <rect
        x="20"
        y="31"
        width="3"
        height="3"
        rx="0.5"
        fill="#8b1a3f"
        opacity="0.4"
      />
      <rect
        x="26"
        y="31"
        width="3"
        height="3"
        rx="0.5"
        fill="#8b1a3f"
        opacity="0.4"
      />
      <path
        d="M12 15 L15 23 L18 17 L21 23 L24 15"
        stroke="#df4b70"
        strokeWidth="1.8"
        strokeLinecap="round"
        strokeLinejoin="round"
        fill="none"
      />
      <path d="M20 26 L14 35 L26 35 Z" fill="#8b1a3f" opacity="0.15" />
    </svg>
  );
}
